name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Just command runner
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 liblua5.1-0-dev luarocks

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: false

      - name: Install Luacheck
        run: sudo luarocks install luacheck

      - run: just lint

      - run: just fmt && git diff --exit-code
