name: Lua CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Lua and LuaRocks
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install Luacheck
        run: luarocks install luacheck

      - name: Install lua-language-server
        run: |
          # Get the latest release version
          LATEST_VERSION=$(curl -s https://api.github.com/repos/LuaLS/lua-language-server/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          wget "https://github.com/LuaLS/lua-language-server/releases/latest/download/lua-language-server-${LATEST_VERSION}-linux-x64.tar.gz"
          tar -xzf "lua-language-server-${LATEST_VERSION}-linux-x64.tar.gz"
          sudo cp bin/lua-language-server /usr/local/bin/
          sudo chmod +x /usr/local/bin/lua-language-server
          lua-language-server --version

      - name: Install Just command runner
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Run comprehensive linting
        run: just lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install StyLua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/

      - name: Check formatting
        if: failure()
        run: echo "::error::Code is not formatted. Run 'stylua lua/' locally to format."

