name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim:
          - v0.10.0
          - nightly

    steps:
      - uses: actions/checkout@v4

      - name: Install Just command runner
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - run: nvim --version

      - name: Setup dependencies
        run: just deps-mini-nvim

      - name: Run tests
        shell: bash
        run: |
          set -o pipefail
          nvim --version | tee test-results.log
          just test 2>&1 | tee -a test-results.log

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.neovim }}
          path: test-results.log
