name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim:
          - v0.10.0
          - nightly

    steps:
      - uses: actions/checkout@v4

      - name: Install Just command runner
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - name: Install mini.nvim
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/deps/start
          git clone --filter=blob:none https://github.com/echasnovski/mini.nvim ~/.local/share/nvim/site/pack/deps/start/mini.nvim

      - run: nvim --version

      - run: just test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.neovim }}
          path: test-results.log
          retention-days: 7

